### ISSUE TITLE
How does importing work?

### ISSUE THREAD

**Issue by themeteorchef** [aaronagray/meteor-susy#1]
Trying to get everything setup and following your docs ran:
1. `meteor add meta:susy`
2. `gem install compass`

Both succeed as expected. Then, in the app, adding:

`@import "susy";` doesn't appear to work. I've tried this in a few different spots in the file tree (both project root and in my `/client` folder).

Looking at the source, it doesn't look like Susy is being loaded on the client and [only on the server](https://github.com/aaronagray/meteor-susy/blob/master/package.js#L77)?

Am I missing something/being a dummy? Thanks!

**Comment by samusgray** [comment]
That's right. Susy is loaded into the server since it's preprocessed and only adds client code when included / imported in your .scss files. 

However, Susy depends on the latests Sass features which are a work-in-progress for Lib Siass & node-sass, so this meta:susy package is stuck until Lib Sass, Node Sass, and meteor:scss are in feature parity. 

It looks like meteor:scss just merged the latest Node Sass today, so I plan to test it out and hopefully get this package importing Susy again. I'll leave this issue open, update the installation steps, and send an update here once everything is running again this week.

**Comment by themeteorchef** [comment]
Cool, thanks for the quick response. I'll keep an eye out :)

**Comment by samusgray** [comment]
@themeteorchef node-sass, libsass, and ruby sass are all finally in feature parity! I'll have this back up and running tomorrow if all goes well.

**Comment by themeteorchef** [comment]
@aaronagray awesome! Appreciate the update :) Excited to use this.

**Comment by samusgray** [comment]
All set! Feel free to try installing this with `meteor add meta:susy`. I also update the docs to show how to import Susy after it is installed.
