### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by nalply** [aaronagray/meteor-susy#2]
Examples would be nice.

Something like a minimal Meteor website using Susy to get started.

Perhaps create another github repository and link to it from the readme?

Sorry if it's already there.

**Comment by samusgray** [comment]
Hey @nalply, I removed the Compass dependance and simplified things a bit. I'll include better documentation for this and send an update tomorrow.

**Comment by samusgray** [comment]
Hey @nalply, There are only two steps to get set up with Susy, so I've updated the documentation. I've also removed the Compass gem dependency, so things should be easier all around. Please let me know if you have any specific questions about getting started! 

Otherwise, check out the [Susy documentation](http://susydocs.oddbird.net/en/latest/) for Susy specifics and check out the [fourseven:scss documentation](https://github.com/fourseven/meteor-scss) for Sass setup specifics.
